# Generated by Django 2.0.2 on 2018-02-07 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='artist',
            field=models.ManyToManyField(related_name='album_list', to='artist.Artist'),
        ),
    ]
