# Generated by Django 2.0.2 on 2018-02-08 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0003_auto_20180208_1102'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='genre',
            field=models.CharField(blank=True, max_length=50, verbose_name='장르'),
        ),
    ]
