# Generated by Django 2.0.2 on 2018-02-07 03:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artist', '0002_auto_20180206_1655'),
        ('album', '0002_auto_20180207_1225'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtistSong',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('demo_date', models.DateField()),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artist.Artist')),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('lyrics', models.TextField(blank=True)),
                ('composer', models.CharField(max_length=50, verbose_name='작곡')),
                ('lyricist', models.CharField(max_length=50, verbose_name='작사')),
                ('arranger', models.CharField(max_length=50, verbose_name='편곡')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='album.Album')),
                ('artist', models.ManyToManyField(related_name='song_list', through='song.ArtistSong', to='artist.Artist')),
            ],
        ),
        migrations.AddField(
            model_name='artistsong',
            name='song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='song.Song'),
        ),
    ]
