# Generated by Django 2.0.2 on 2018-02-08 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='artist',
        ),
        migrations.AddField(
            model_name='song',
            name='genre',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='song',
            name='arranger',
            field=models.CharField(blank=True, max_length=50, verbose_name='편곡'),
        ),
        migrations.AlterField(
            model_name='song',
            name='composer',
            field=models.CharField(blank=True, max_length=50, verbose_name='작곡'),
        ),
        migrations.AlterField(
            model_name='song',
            name='lyricist',
            field=models.CharField(blank=True, max_length=50, verbose_name='작사'),
        ),
    ]
