# Generated by Django 2.0.2 on 2018-02-06 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='생년월일'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='img_profile',
            field=models.ImageField(blank=True, upload_to='artist', verbose_name='프로필 이미지'),
        ),
    ]
